# Get all books
GET http://localhost:3001/books HTTP/1.1
Content-Type: application/json

###

# Create a book
POST http://localhost:3001/books HTTP/1.1
Content-Type: application/json

{
  "title": "Book 3",
  "author": "author 3",
  "yearPublished": 2022
}

###

# Get all movies
GET http://localhost:3001/movies HTTP/1.1
Content-Type: application/json

###

# Create a movie
POST http://localhost:3001/movies HTTP/1.1
Content-Type: application/json

{
  "title": "Superman"
}